# Generated by Django 2.1.7 on 2019-04-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image1', models.CharField(max_length=255)),
                ('image2', models.CharField(max_length=255)),
                ('image3', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('productid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image1', models.CharField(max_length=255)),
                ('image2', models.CharField(max_length=255)),
                ('image3', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('quantityprice', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkUserid', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('deliverycharged', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customeraddress',
            },
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('productid', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('quantityprice', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='ProductOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('productid', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('quantityprice', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'productordered',
            },
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkProductid', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('updatedate', models.CharField(max_length=20)),
                ('updatetime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subproduct',
            },
        ),
    ]
