# Generated by Django 2.1.7 on 2019-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image1', models.CharField(max_length=255)),
                ('image2', models.CharField(max_length=255)),
                ('image3', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
