# Generated by Django 2.1.7 on 2019-04-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='price',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
