# Generated by Django 2.1.7 on 2019-03-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
