# Generated by Django 2.1.7 on 2019-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_auto_20190403_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordered',
            name='category',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
