# Generated by Django 2.1.7 on 2019-03-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='repassword',
            new_name='gender',
        ),
    ]
