# Generated by Django 2.1.7 on 2019-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_productordered_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkAttr', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('deliverycharge', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('key', models.ForeignKey(null=True, on_delete='Do Nothing', to='module1.ProductOrdered')),
            ],
            options={
                'db_table': 'customeraddress',
            },
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='country',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='state',
        ),
    ]
