# Generated by Django 2.1.7 on 2019-04-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_auto_20190404_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='deliverycharge',
            new_name='deliverycharged',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='key',
        ),
        migrations.RemoveField(
            model_name='productordered',
            name='address',
        ),
        migrations.RemoveField(
            model_name='productordered',
            name='city',
        ),
        migrations.RemoveField(
            model_name='productordered',
            name='country',
        ),
        migrations.RemoveField(
            model_name='productordered',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='productordered',
            name='state',
        ),
    ]
