# Generated by Django 2.1.7 on 2019-03-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_auto_20190329_1304'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logindata',
            table='logindata',
        ),
    ]
