# Generated by Django 2.1.7 on 2019-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_auto_20190404_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkProductid', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('updatedate', models.CharField(max_length=20)),
                ('updatetime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'productsizecolor',
            },
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='Lblack',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='Lblue',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='Mblack',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='Mblue',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='Sblack',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='Sblue',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='XLblack',
        ),
        migrations.RemoveField(
            model_name='addproduct',
            name='XLblue',
        ),
    ]
