# Generated by Django 2.1.7 on 2019-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_auto_20190404_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizeColor',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='color',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addproduct',
            name='quantity',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addproduct',
            name='size',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
